codesquad-project-team/backend

app.js
package-lock.json
package.json
swagger/swagger-api.yaml
swagger/swagger-definition.js

- URL : /api-docs
- /swagger/swagger-api.yaml 수정하여 사용

[feat] swagger 세팅 완료

---

app.js
migrations/20191002031823-create-user.js
migrations/20191002063214-create-post.js
migrations/20191002071458-create-image.js
migrations/20191002071714-create-location.js
models/image.js
models/index.js
models/location.js
models/post.js
models/user.js
package-lock.json
package.json
src/database/migrations/20191002031823-create-user.js
src/database/migrations/20191002063214-create-post.js
src/database/migrations/20191002071458-create-image.js
src/database/migrations/20191002071714-create-location.js

post, user, image, location 모델 작성
마이그레이션 작성

Issue/5 model schema 작성

---

app.js
models/fakeDB.js
routes/post.js

GET post/related-to API 생성
- fake db와 dummy data를 이용한 api 생성

Issue/16 GET post/related-to API 생성

---

models/index.js
swagger/swagger-api.yaml

GET post/related-to API 생성
- fake DB 와 dummy data 를 이용한 api 생성

임시 GET post/related-to API 생성

---

app.js
package-lock.json
package.json

feat : CORS 허용

---

models/post.js
src/database/migrations/20191002063214-create-post.js

refactor : post table model 수정

---

routes/post.js

- response 형식 html -> json 으로 변경

refactor : response 형식 변경

---

swagger/swagger-api.yaml

[feat] get random posts api swagger 작성

---

ecosystem.config.js
package-lock.json
package.json

- watch 기능 On, node_modules, README 는 ignore

[feat] pm2 start ecosystem config 방식으로 변경

---

app.js
package-lock.json
routes/user.js
routes/users.js
swagger/swagger-api.yaml

- GET /user/info
- JWT 를 사용하여 로그인한 사용자의 정보를 가져옴
- 현재는 JWT구현되어 있지 않으므로 fake 로 사용

[feat] get user info api

---

app.js
package-lock.json
routes/user.js
routes/users.js
src/paginatior.js
swagger/swagger-api.yaml

GET /user/info
JWT 를 사용하여 로그인한 사용자의 정보를 가져옴
현재는 JWT구현되어 있지 않으므로 fake 로 사용

GET /user/info

---

routes/post.js
swagger/swagger-api.yaml

- latitude, longitude type string => float
- url typo error fix

[fix] get full post info api

---

models/index.js
package.json
src/database/seeders/20191024085931-follow.js

[feat] follow seeder 생성

---

app.js
controllers/auth.js
controllers/index.js
middlewares/index.js
models/user.js
package-lock.json
package.json
passport/facebook.js
passport/index.js
passport/kakao.js
routes/apiv1/auth.js
routes/apiv1/index.js
src/database/migrations/20191002031823-create-user.js
src/database/seeders/20191010032325-myFirstSeed.js

Oauth 로그인 구현
- kakao, facebook Oauth 로그인 구현
JWT 로그인 구현

[Issue/78] Oauth, JWT 로그인 구현

---

passport/facebook.js
passport/kakao.js

facebook, kakao client id, secret 제거

fix : id, secret 제거

---

src/database/migrations/create-follow.js

[Issue/93] migration follow 테이블 column 명 변경

---

controllers/post.js
routes/apiv1/post.js
src/paginatior.js
swagger/apiv1/swagger-api.yaml

- response에 hasNextPage property 추가
- paginator에 where 조건절 obtion 추가
- parseRealtedData function 수정
- postid query 수정(post-id => postid)

[feat] related-post pagination 기능 추가

---

app.js
passport/facebook.js
passport/kakao.js
routes/apiv1/user.js
swagger/apiv1/swagger-api.yaml
swagger/apiv1/swagger-definition.js

- apiv1 => v1
- GET /user/info => GET /user/myinfo

[fix] url 수정

---

routes/apiv1/post.js
swagger/apiv1/swagger-api.yaml

- writerid 가 query 로 있으면 where 추가.

[feat] get page 에 특정 작성자 옵션 추가

---

routes/apiv1/auth.js

[Issue/78] cookie domain 설정

---

app.js
middlewares/index.js
passport/facebook.js
passport/kakao.js
routes/apiv1/auth.js
routes/apiv1/index.js
swagger/apiv1/swagger-api.yaml

닉네임 입력 방식 변경
- 필수 입력에서 1회성 입력으로 변경

[Issue/97] 로그인 절차 변경

---

app.js
middlewares/index.js
passport/facebook.js
passport/kakao.js
routes/apiv1/auth.js
routes/apiv1/index.js
swagger/apiv1/swagger-api.yaml

[Issue/97] regiesterNickname 미들웨어 삭제

---

app.js
cors/index.js

- whiteList 생성
- credentials 옵션 true

[issue/112] cors option 추가

---

passport/kakao.js

[issue/118] fix : url 오류수정

---

routes/apiv1/post.js

[issue/113] fix : 오류 수정

---

routes/apiv1/auth.js
swagger/apiv1/swagger-api.yaml

[Issue/90] POST /auth/logout 추가

---

routes/apiv1/index.js
routes/apiv1/validate.js
swagger/apiv1/swagger-api.yaml

- validate router 추가
- POST /validate/nickname 추가
- POST /validate/tempToken 추가
- swagger 문서 추가

[Issue/122] validate router 추가

---

src/database/seeders/20191010032325-myFirstSeed.js

- refactor : user, post 갯수 늘리기

[issue/126] seed 수정

---

swagger/apiv1/swagger-api.yaml

[Issue/129] SWAGGER 설명 추가

---

controllers/auth.js
passport/facebook.js
passport/kakao.js
routes/apiv1/auth.js
routes/apiv1/validate.js
swagger/apiv1/swagger-api.yaml

- 쿠키, 토큰 만료시간 통일
- controller login, tempLogin 추가
- validate/token 응답 provider 추가

[Issue/131] 로그인 회원가입 리팩토링

---

routes/apiv1/auth.js

[issue/136]fix : 회원 조회 오류 수정

---

routes/apiv1/validate.js

fix : tempToken 검증 api 오류 수정

---

models/image.js
models/location.js
models/post.js
models/user.js
src/database/migrations/20191002031823-create-user.js
src/database/migrations/20191002051714-create-location.js
src/database/migrations/20191002063214-create-post.js
src/database/migrations/20191002071458-create-image.js
src/database/migrations/create-follow.js

- paranoid : true 추가
- post table : title_location 추가
- location table : external link 삭제

[Issue/141] DB table 수정

---

src/database/migrations/20191002031823-create-user.js
src/database/migrations/20191002051714-create-location.js
src/database/migrations/20191002063214-create-post.js
src/database/migrations/20191002071458-create-image.js
src/database/migrations/create-follow.js
src/database/seeders/20191010032325-myFirstSeed.js

fix : 오류 수정

---

models/follow.js
models/index.js

fix : follow 테이블 수정

---

controllers/auth.js
routes/apiv1/auth.js
swagger/apiv1/swagger-api.yaml

[issue/155] refactor : 회원가입, 로그아웃 응답 변경

---

controllers/auth.js
routes/apiv1/auth.js

- 로그인 메소드가 회원가입, 로그인시 다르게 작용하도록 변경

[issue/155] refactor : 로그인 메소드 수정

---

controllers/auth.js
routes/apiv1/auth.js
swagger/apiv1/swagger-api.yaml

[issue/155] 로그인 메소드 수정

---

controllers/auth.js
routes/apiv1/auth.js

fix : res.json 수정

---

models/follow.js
src/database/migrations/create-follow.js
src/database/seeders/20191024085931-follow.js

refactor : follow 테이블 수정

---

app.js
controllers/auth.js
middlewares/index.js
routes/apiv1/auth.js
routes/apiv1/index.js
swagger/apiv1/swagger-api.yaml

- middleware 의존방싱 변경
- isLoggedIn 미들웨어 생성
- 로그인 token 정보 변경
- sawgger 문서 수정

[Issue/164] /auth/has-logged-in api 추가

---

swagger/apiv1/swagger-api.yaml

fix : id type 오류 수정

---

routes/apiv1/auth.js

fix : token 오류 수정

---

routes/apiv1/user.js

- req.decoded 가 없으면 id 를 읽지 않도록 수정

fix : id 없는 에러 수정

---

routes/apiv1/user.js
swagger/apiv1/swagger-api.yaml

req.decoded 가 없으면 id를 읽지 않도록 수정

fix : id 가 없는 에러 수정

---

routes/apiv1/post/post-ctrl.js
swagger/apiv1/swagger-definition.js

swagger host address도 변경함. swagger에서 api test 가능하게 해보려고

[feat] postCreate의 location 에 link, phone 필드 추가

---

routes/apiv1/post/index.js
routes/apiv1/post/post-ctrl.js

[feat] postcreate, postupdate error 처리

---

routes/apiv1/post/index.js
routes/apiv1/post/post-ctrl.js

기존 image array에 url 만 담아서 보내던 것을 image object list를 보내도록 수정.
image object 는 url, isRepresentative 정보 포함.

Issue/222 getPost response 에 isRepresentative property 추가

---

routes/apiv1/post/index.js
routes/apiv1/post/post-ctrl.js

[refactor]getPost response 변경

---

routes/apiv1/user/index.js
routes/apiv1/user/user-ctrl.js

1. isMyProfile 삭제하고 user id를 추가했음.
2. nickname으로 찾을 수 있도록 쿼리 수정했음.

Issue/235 getProfileContent 수정

---

routes/apiv1/user/index.js
routes/apiv1/user/user-ctrl.js

Method: GET
URL : /user/{id}/relationship/{type}
type: follower || following
id: user id

Issue/240 follower/following 목록 조회하기

---

middlewares/index.js
routes/apiv1/auth/auth-ctrl.js
routes/apiv1/user/user-ctrl.js

- close #243
- sameSite :none 옵션 추가

feat : 쿠키에 sameSite 옵션 추가
